### ISSUE TITLE
Vision

### ISSUE THREAD

**Issue by KozlovKV** [FIT-2024-RecALL/RecALL-docs#1]
[Ссылка](https://docs.google.com/document/d/1Hbe8_xYmQzBLVV-6A9pXLAhF-YWI5mEHQLPw9L9kGvM/edit?usp=sharing)

**Comment by AntonTsoy** [comment]
Интересное видео: https://www.youtube.com/watch?v=tCBbGbRvkGo
Автор критикует анки карточки (там он дал более крутой термин SRS - Spaced Repetition System). Он критикует не саму по себе концепцию интервального повторения, а анки soft.
Если разобрать его критику по пунктам, то на каждый пункт можно придумать фичу, которая нивелирует всю критику.

**Comment by AntonTsoy** [comment]
Wiki о утилите, которая может стать для нас примером того, что нужно реализовывать: https://learnanylanguage.fandom.com/wiki/Subs2srs
